services:
  - type: web
    name: confind-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon
    branch: main
    rootDir: .
    env:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000 